# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-19 09:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_caption', models.CharField(max_length=100, verbose_name=b'\xe8\xae\xbe\xe5\xa4\x87\xe5\x90\x8d\xe7\xa7\xb0')),
                ('device_serial', models.CharField(max_length=100, verbose_name=b'\xe8\xae\xbe\xe5\xa4\x87\xe5\xba\x8f\xe5\x88\x97\xe5\x8f\xb7')),
                ('device_type', models.CharField(max_length=50, verbose_name=b'\xe8\xae\xbe\xe5\xa4\x87\xe5\x9e\x8b\xe5\x8f\xb7')),
                ('device_vendor', models.CharField(choices=[(b'CISCO', b'CISCO'), (b'JUNIPER', b'JUNIPER'), (b'TOPSEC', b'TOPSEC'), (b'HUAWEI', b'HUAWEI'), (b'H3C', b'H3C')], max_length=50, verbose_name=b'\xe8\xae\xbe\xe5\xa4\x87\xe5\x8e\x82\xe5\x95\x86')),
                ('device_remark', models.CharField(blank=True, max_length=50, verbose_name=b'\xe5\xa4\x87\xe6\xb3\xa8')),
                ('device_ip', models.GenericIPAddressField(verbose_name=b'\xe7\xae\xa1\xe7\x90\x86IP')),
                ('device_status', models.CharField(default=b'\xe5\x90\xaf\xe7\x94\xa8', max_length=10, verbose_name=b'\xe8\xae\xbe\xe5\xa4\x87\xe7\x8a\xb6\xe6\x80\x81')),
                ('device_signer', models.CharField(default=b'system', max_length=30, verbose_name=b'\xe7\x99\xbb\xe8\xae\xb0\xe4\xba\xba')),
                ('device_signtime', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_code', models.CharField(max_length=100, verbose_name=b'\xe7\xba\xbf\xe8\xb7\xaf\xe7\xbc\x96\xe5\x8f\xb7')),
                ('line_local', models.CharField(default=b'\xe4\xb8\x8a\xe6\xb5\xb7\xe6\x95\xb0\xe6\x8d\xae\xe4\xb8\xad\xe5\xbf\x83', max_length=50, verbose_name=b'\xe6\x89\x80\xe5\x9c\xa8\xe6\x9c\xba\xe6\x88\xbf')),
                ('line_speed', models.CharField(choices=[(b'2M', b'2M'), (b'4M', b'4M'), (b'6M', b'6M'), (b'10M', b'10M'), ('\u5176\u4ed6', b'\xe5\x85\xb6\xe4\xbb\x96')], default=b'6M', max_length=10, verbose_name=b'\xe7\xba\xbf\xe8\xb7\xaf\xe9\x80\x9f\xe7\x8e\x87')),
                ('line_spname', models.CharField(choices=[('\u4e2d\u56fd\u7535\u4fe1', b'\xe4\xb8\xad\xe5\x9b\xbd\xe7\x94\xb5\xe4\xbf\xa1'), ('\u4e2d\u56fd\u8054\u901a', b'\xe4\xb8\xad\xe5\x9b\xbd\xe8\x81\x94\xe9\x80\x9a'), ('\u4e2d\u56fd\u79fb\u52a8', b'\xe4\xb8\xad\xe5\x9b\xbd\xe7\xa7\xbb\xe5\x8a\xa8'), ('\u4e2d\u56fd\u94c1\u901a', b'\xe4\xb8\xad\xe5\x9b\xbd\xe9\x93\x81\xe9\x80\x9a'), ('\u5176\u4ed6', b'\xe5\x85\xb6\xe4\xbb\x96')], default=b'\xe4\xbf\xa1\xe7\xbd\x91\xe5\x85\xac\xe5\x8f\xb8', max_length=10, verbose_name=b'\xe8\xbf\x90\xe8\x90\xa5\xe5\x95\x86')),
                ('line_type', models.CharField(choices=[(b'MSTP', b'MSTP'), (b'MSAP', b'MASP'), (b'SDH', b'SDH'), (b'DIAL', b'DIAL'), ('\u5176\u4ed6', b'\xe5\x85\xb6\xe4\xbb\x96')], default=b'MSTP', max_length=50, verbose_name=b'\xe7\xba\xbf\xe8\xb7\xaf\xe7\xb1\xbb\xe5\x9e\x8b')),
                ('line_status', models.BooleanField(default=True, verbose_name=b'\xe7\xba\xbf\xe8\xb7\xaf\xe5\x90\xaf\xe7\x94\xa8')),
                ('line_open', models.DateField(verbose_name=b'\xe5\xbc\x80\xe9\x80\x9a\xe6\x97\xb6\xe9\x97\xb4')),
                ('line_closed', models.DateField(blank=True, null=True, verbose_name=b'\xe5\x85\xb3\xe9\x97\xad\xe6\x97\xb6\xe9\x97\xb4')),
                ('line_signer', models.CharField(default=b'system', max_length=30, verbose_name=b'\xe7\x99\xbb\xe8\xae\xb0\xe4\xba\xba')),
                ('line_signtime', models.DateField(auto_now_add=True)),
                ('line_remarks', models.CharField(blank=True, max_length=255, verbose_name=b'\xe5\xa4\x87\xe6\xb3\xa8')),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_name', models.CharField(max_length=255, verbose_name=b'\xe8\x8a\x82\xe7\x82\xb9\xe5\x90\x8d\xe7\xa7\xb0')),
                ('node_type', models.CharField(choices=[('\u603b\u90e8', b'\xe6\x80\xbb\xe9\x83\xa8'), ('\u5206\u90e8', b'\xe5\x88\x86\xe9\x83\xa8')], max_length=50, verbose_name=b'\xe8\x8a\x82\xe7\x82\xb9\xe7\xb1\xbb\xe5\x9e\x8b')),
                ('node_address', models.CharField(max_length=255, verbose_name=b'\xe8\x8a\x82\xe7\x82\xb9\xe5\x9c\xb0\xe5\x9d\x80')),
                ('node_contact', models.CharField(blank=True, max_length=255, verbose_name=b'\xe8\x8a\x82\xe7\x82\xb9\xe8\x81\x94\xe7\xb3\xbb\xe4\xba\xba')),
                ('node_signer', models.CharField(default=b'system', max_length=50, verbose_name=b'\xe7\x99\xbb\xe8\xae\xb0\xe4\xba\xba')),
                ('node_remarks', models.CharField(blank=True, max_length=255, verbose_name=b'\xe5\xa4\x87\xe6\xb3\xa8')),
                ('node_signtime', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='line',
            name='node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ace.Node'),
        ),
        migrations.AddField(
            model_name='device',
            name='node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ace.Node'),
        ),
    ]
